.global _ZN6_riscV13pushRegistersEv
.type _ZN6_riscV13pushRegistersEv, @function
_ZN6_riscV13pushRegistersEv:
    addi sp, sp, -256
    .irp index, 3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31
    sd x\index, \index * 8(sp)
    .endr
    ret

.global _ZN6_riscV12popRegistersEv
.type _ZN6_riscV12popRegistersEv, @function
_ZN6_riscV12popRegistersEv:
    .irp index, 3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31
    ld x\index, \index * 8(sp)
    .endr
    addi sp, sp, 256
    ret
